class TokenType:
    WHITESPACE = 'whitespace'
    KEYWORD = 'keyword'
    STRING = 'string'
    RESERVED_KEYWORD = 'reserved-keyword'
    TOP_LEVEL_KEYWORD = 'top-level-keyword'
    TOP_LEVEL_KEYWORD_NO_INDENT = 'top-level-keyword-no-indent'
    NEWLINE_KEYWORD = 'newline-keyword'
    OPERATOR = 'operator'
    OPEN_PAREN = 'open-paren'
    CLOSE_PAREN = 'close-paren'
    LINE_COMMENT = 'line-comment'
    BLOCK_COMMENT = 'block-comment'
    NUMBER = 'number'
    PLACEHOLDER = 'placeholder'